### ISSUE TITLE
Are these binaries Universal (Intel and ARM)?

### ISSUE THREAD

**Issue by hiulit** [huskeee/godot-headless-mac#5]
Also, I wanted to thank you for these binaries! :D
I'm using them with my own export tool and they work great! I don't know what you do to compile them but they work better than my own compilations. Yours don't get block by GateKeeper and mine do :/

**Comment by huskeee** [comment]
AFAIK GitHub Actions' macOS machines are Intel based, so I think my binaries are Intel only.
Also, if you check the workflow file in this repo, you'll find out the exact commands that are used to compile my binaries.

Thank you for your kind words :heart:

**Comment by huskeee** [comment]
Also, official (and probably universal) headless builds for macOS are coming in Godot 4.0, so you won't have to wait for long :D
